AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Bucket:
    Type: AWS::S3::Bucket
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: service.handler
      Runtime: python3.6
      CodeUri: service.zip
      Environment:
        Variables:
          BUCKET: !Ref Bucket
      Events:
        Cron:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:GetObject
          - s3:ListBucket
          - s3:PutObject
          - s3:PutObjectAcl
          Resource:
          - !Sub 'arn:aws:s3:::${Bucket}'
          - !Sub 'arn:aws:s3:::${Bucket}/*'
Outputs:
  BucketName:
    Description: Bucket Name
    Value: !Ref Bucket
